<meta charset="utf-8">
<title>Titash Livepics</title>

<!-- Meta -->
<meta name="title" content="Titash LivePics" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<meta name="description" content="Titash Art & Creations (cartooniste, webdesigner et créateur multimedia en Freelance)." />
<meta name="keywords" content="titash,art,jonathan,franczyk,freelance,illustrations,drawing,badges,webcomics,comics,strips,livepic,work in progress,sketchbook,costume,performing,publishing,pao,dtp,web design,motion design,creation,photo,video,news,events,évènements,pucky,pistash,krabouille,suricate,meerkat" />
<meta name="category" content="blog,art,gallery,cartoon,portfolio,drawing,entertainment" />
<meta name="owner" content="Titash - Jonathan Franczyk" />
<meta name="author" content="Titash - Jonathan Franczyk" />
<meta name="webmaster" content="Titash - Jonathan Franczyk" />
<meta name="identifier-URL" content="http://www.titash.net/livepic" />
<meta name="copyright" content="Titash - Jonathan Franczyk" />
<meta name="rating" content="General">
<meta name="robots" content="all" />
<meta name="revisit-after" content="1 days" />
<meta name="expires" content="never" />
<meta name="Language" content="fr,en" />
<meta http-equiv="content-language" content="fr,en" />

<!-- Styles -->
<link href="http://www.titash.net/livepic/style.css" rel="stylesheet" type="text/css" />
<link href="http://www.titash.net/livepic/fonts/stylesheet.css" rel="stylesheet" type="text/css" />

<!-- MultiDevices Favicon -->
<link rel="apple-touch-icon" sizes="57x57" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="http://www.titash.net/tsh/icons/livepic/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="http://www.titash.net/tsh/icons/livepic/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="http://www.titash.net/tsh/icons/livepic/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="http://www.titash.net/tsh/icons/livepic/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="http://www.titash.net/tsh/icons/livepic/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="http://www.titash.net/tsh/icons/livepic/manifest.json">
<link rel="shortcut icon" href="http://www.titash.net/tsh/icons/livepic/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Titash Livepics">
<meta name="application-name" content="Titash Livepics">
<meta name="msapplication-TileColor" content="#d4cfcb">
<meta name="msapplication-TileImage" content="http://www.titash.net/tsh/icons/livepic/mstile-144x144.png">
<meta name="msapplication-config" content="http://www.titash.net/tsh/icons/livepic/browserconfig.xml">
<meta name="theme-color" content="#d4cfcb">

<!-- Twitter Summary Card -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@TitashMeerkat" />
<meta name="twitter:creator" content="@TitashMeerkat" />
<meta name="twitter:title" content="Titash LivePics" />
<meta name="twitter:description" content="Titash Art & Creation" />
<meta name="twitter:image" content="http://www.titash.net/tsh/icons/livepic/twitter.png" />
<meta name="twitter:url" content="http://www.titash.net/livepic" />

<!-- Facebook Preview -->
<meta property="og:title" content="Titash LivePics" />
<meta property="og:site_name" content="Titash" />
<meta property="og:description" content="Titash Art & Creation" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://www.titash.net/livepic" />
<meta property="og:image" content="http://www.titash.net/tsh/icons/livepic/facebook.png" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="400px" />
<meta property="og:image:height" content="400px" />

<!-- Lightbox -->
<link href="http://www.titash.net/tsh/script/lightbox/lightbox.css" rel="stylesheet" type="text/css" />

<!-- Jquery -->
<script type="text/javascript" src="http://www.titash.net/tsh/script/jquery.js"></script>

<!-- Social Sharing -->
<script src="https://apis.google.com/js/platform.js" async defer></script>

<!-- Responsive Mobile Menu -->
<link rel="stylesheet" href="http://www.titash.net/tsh/script/responsivemobilemenu/rmm-css/responsivemobilemenu.css" type="text/css"/>
<script type="text/javascript" src="http://www.titash.net/tsh/script/responsivemobilemenu/rmm-js/responsivemobilemenu.js"></script>

