<?php
define('SORT_ORDER_DESC', 'none', true);
define('SORT_ORDER_ASC', 'rev', true);

/*
 *  Ordre de classement possibles pour les LP.
 */
$availableSortOrder = [
    SORT_ORDER_DESC => 'most recent Livepic first',
    SORT_ORDER_ASC  => 'oldest Livepic first',
];

/*
 *  Personnages disponibles pour du filtrage de LP.
 */
$availableCharacters = [
  'Titash',
  'Pucky',
];

/*
 *  Méthode de classement des LP.
 *
 *  Si un ordre de classement valide est passé dans l’URL, on s’en sert.
 *  Sinon, on classe par ordre anti-chronologique (DESC).
 */
if (isset($_GET['sort']) && in_array($_GET['sort'], array_keys($availableSortOrder))) {
    $currentSort = $_GET['sort'];
} else {
    $currentSort = SORT_ORDER_DESC;
}

/*
 *  Méthode de filtrage des LP.
 *
 *  Si un filtre (de personnages) valide est passé dans l’URL, on s’en sert.
 *  Sinon, on demande à afficher tous les personnages sans filtre.
 */
if (isset($_GET['show']) && in_array($_GET['show'], $availableCharacters)) {
    $currentFilter = $_GET['show'];
} else {
    $currentFilter = 'all';
}

// On récupère le contenu du fichier XML, suivant l’ordre de tri demandé
if ($currentSort == SORT_ORDER_ASC) {
    $livepics = array_reverse($this->lpXML->xpath('livepic'));
} else { // if ($currentSort == DESC)
    $livepics = $this->lpXML->xpath('livepic');
}

// Nombre total de LP, nécessaire pour des calculs
$lpNumTotal = count($livepics);
?>

<!-- Sort and filter Livepics -->
<div id="gallery-sorting">
<form id="gallery-sorting-form" action=".">
<p>
  Showing
    <select name="sort" onchange="this.form.submit()">
      <?php
        foreach($availableSortOrder as $o => $desc):
            $selected = ($currentSort == $o) ? 'selected="selected"' : '';
            echo "<option value=\"$o\" $selected>$desc</option>" . PHP_EOL;
        endforeach;
      ?>
    </select>
    <noscript><button type="submit">Sort</button></noscript>
  .

  See
    <?php
      array_unshift($availableCharacters, 'all');
      foreach($availableCharacters as $char):
          $disabled = ($char == $currentFilter) ? 'disabled="disabled"' : '';
          if ($char == 'all'):
              echo "<button name=\"show\" value=\"all\" $disabled>everyone</button>";
          else:
              echo "<button name=\"show\" value=\"$char\" $disabled>$char</button>";
          endif;
      endforeach;
    ?>
  .
</p>
</form>
</div>

<div class="gallery-list">

<?php $lpPos = 0; ?>
<?php foreach($livepics as $lp):
    $lpPos++;
    $lpNum = ($currentSort == SORT_ORDER_DESC) ? $lpNumTotal - $lpPos + 1: $lpPos; // Numéro de la Livepic
    $lpTitle = htmlspecialchars($lp->title); // Appeler htmlspecialchars à cause des caractères < ou & qui seraient interprétés comme HTML

    if ($lp->attributes()->{'disabled'} == "yes") {
      continue; // On saute chaque <livepic disabled="yes">
    }
?>

  <figure class="gallery-item gallery-item-bloglink_img">
      <a href="<?= $this->LP_URL ?>/livepic/Titash%20<?= sprintf('%03d', $lpNum) ?>%20LivePic%20<?= $lp->date ?>.jpg" data-imagelightbox="pic" title="Livepic <?= $lpNum ?>">
          <img alt="<?= $lpTitle ?>" src="<?= $this->LP_URL ?>/preview/Titash%20<?= sprintf('%03d', $lpNum) ?>%20LivePic%20<?= $lp->date ?>.jpg">
      </a>
      <figcaption class="gallery-item-bloglink">
          <a href="http://www.titash.net/blog/titash-livepic-<?= $lpNum ?>/">
              Livepic <?= $lpNum ?>
              <span class="gallery-item-bloglink_date"><?= $lp->date ?></span>
          </a>
      </figcaption>
  </figure>

<?php endforeach; ?>

</div>
