<!-- TitashBar -->
<!-- TitashBar : LinkBar -->
<nav>
    <div id="tashbar-link">
        <div id="tashbar-link-content">
            <div class="rmm" data-menu-style="minimal">
<ul>
<!--<li><a href='http://wwww.titash.net'>Titash</a></li><li><a href='#'>Portfolio</a></li><li><a href='#'>TimeLine</a></li>--><li><a href='http://www.titash.net/blog' target="_self" >Art Blog</a></li><li><a href='http://www.titash.net/pro'>Pro</a></li><!--<li><a href='#'>Shopping</a></li>-->
</ul>
            </div><!-- CSS/ rmm -->
        </div><!-- CSS/ tashbar-link-content -->
    </div><!-- CSS/ tashbar-link -->
</nav>

<!-- TitashBar : StickyBar 1/2 -->
<div id="sticky_navigation_wrapper">
    <div id="sticky_navigation">

<!-- TitashBar : NavBar -->
        <nav>
            <div id="tashbar_mini">
                <div id="tashbar-nav"><div id="tashbar-nav-content">
                    <h1><a href="http://www.titash.net/blog"><span id="tashbar-nav-content-title_titash">Titash</span> art blog</a></h1>
                    <div id="tashbar-nav-content-menu">
                        <ul id="tashbar-nav-content-menu_line">                         <li class="tashbar-nav-content-menu_item"><a href="?lang=fr" title="Français / French">Français</a></li>
                            <li class="tashbar-nav-content-menu_item"><a href="?lang=en" title="English / Anglais">English</a></li>                        </ul>
                    </div><!-- CSS/ tashbar-nav-content-menu -->
                </div><!-- CSS/ tashbar-nav-content --></div><!-- CSS/ tashbar-nav -->
            </div><!-- CSS/ tshbar_mini -->
        </nav>

<!-- TitashBar : StickyBar 2/2 -->

    </div><!-- CSS/ sticky_navigation -->
</div><!-- CSS/ sticky_navigation_wrapper -->
